- name: default value
  hosts: all
  become: yes
  vars:
   my_dict:
    course: Terraform
    triner: Jakeer
    duration: 120 hours
  tasks:
    - name: before dict
      debug: 
        msg: "the before brdict is {{ my_dict }}"
    - name: after dict
      debug: 
        msg: "the after dict value is {{ my_dict | dict2iteams }}"    