- name: default value
  hosts: all
  become: yes
  vars:
    number: [25, 35, 45, 55, 65, 75]
  tasks:
    - name: min value
      debug: 
        msg: "the min value is {{ number | min }}"

    - name: max value 
      debug: 
        msg: "the max value is {{ number | max }}"