- name: default value
  hosts: all
  become: yes
  vars:
   my_dict:
      - {'key': 'Course', 'value': 'Ansbile'}
      - {'key': 'Trainer', 'value': 'Sivakumar'}
      - {'key': 'Duration', 'value': '120hr'}
  tasks:
    - name: before dict
      debug: 
        msg: "the before brdict is {{ my_dict }}"
    - name: after dict
      debug: 
        msg: "the after dict value is {{ my_dict | items2dict }}"    