- name: Multitask play-1
  hosts: all
  become: yes
  tasks:
    - name: Play-1
      debug:
        msg: "Hello I am from PLAY-1 and TASK-1"

- name: Multitask play-2
  hosts: all
  become: yes
  tasks:
    - name: Installing httpd
      dnf:
        name: httpd
        state: present

    - name: Starting httpd service
      service:
        name: httpd
        state: started
        enabled: yes