- name: variable it will store the value
  hosts: all
  become: yes
  vars:
    name: Jakeer
    course: AWS 
    duration: 120hrs
  tasks:
  - name: it will override the changes
    course: Devops
    debug:
      msg: "hello i am {{name}}, and i am learning {{course}} duriation is {{duration}}"
  - name: devops course
    debug:
      msg: "hello i am {{name}}, and i am learning {{course}} duriation is {{duration}}"
 